version : '3'
 
services:
  openrmf-web:
    image: cingulara/openrmf-web
    ports:
      - 9080:80
    depends_on:
      - openrmfapi-scoring
      - openrmfapi-save
      - openrmfapi-template
      - openrmfapi-upload
      - openrmfapi-read
      - openrmfapi-compliance

  openrmfapi-scoring:
    image: cingulara/openrmf-api-scoring
    ports:
      - 9090:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - mongoConnection=mongodb://openrmfscore:openrmf1234!@scoredb/openrmfscore?authSource=openrmfscore
      - mongodb=openrmfscore
      - natsserverurl=nats://natsserver:4222
    depends_on:
      - scoredb
      - natsserver

  openrmfmsg-score:
    image: cingulara/openrmf-msg-score
    environment:
      - openrmf-api-read-server=http://openrmfapi-read:8080
      - mongoConnection=mongodb://openrmfscore:openrmf1234!@scoredb/openrmfscore?authSource=openrmfscore
      - mongodb=openrmfscore
      - natsserverurl=nats://natsserver:4222
    depends_on:
      - scoredb
      - natsserver
      - openrmfapi-read
  
  openrmfapi-save:
    image: cingulara/openrmf-api-save
    ports:
      - 9082:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - mongoConnection=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - mongodb=openrmf
      - natsserverurl=nats://natsserver:4222
    depends_on:
      - openrmfmsg-score
      - checklistdb
      - natsserver

  openrmfapi-template:
    image: cingulara/openrmf-api-template
    ports:
      - 9088:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - mongoConnection=mongodb://openrmftemplate:openrmf1234!@templatedb/openrmftemplate?authSource=openrmftemplate
      - mongodb=openrmftemplate
    depends_on:
      - templatedb

  openrmfapi-upload:
    image: cingulara/openrmf-api-upload
    ports:
      - 9086:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - mongoConnection=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - mongodb=openrmf
      - natsserverurl=nats://natsserver:4222
    depends_on:
      - openrmfmsg-score
      - checklistdb
      - natsserver

  openrmfapi-read:
    image: cingulara/openrmf-api-read
    ports:
      - 9084:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - mongoConnection=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - mongodb=openrmf
      - openrmf-api-score-server=http://openrmfapi-scoring:8080
      - openrmf-api-compliance-server=http://openrmfapi-compliance:8080
    depends_on:
      - checklistdb
      - openrmfapi-scoring

  openrmfapi-compliance:
    image: cingulara/openrmf-api-compliance
    ports:
      - 9092:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - openrmf-api-read-server=http://openrmfapi-read:8080
      - openrmf-api-controls-server=http://openrmfapi-controls:8080
    depends_on:
      - openrmfapi-read
      - openrmfapi-controls

  openrmfapi-controls:
    image: cingulara/openrmf-api-controls
    ports:
      - 9094:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080

  checklistdb:
    image: cingulara/openrmf-checklistdb
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmf
    volumes:
      - checklist-data-volume-dev:/data/db

  scoredb:
    image: cingulara/openrmf-scoredb
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmfscore
    volumes:
      - score-data-volume-dev:/data/db

  templatedb:
    image: cingulara/openrmf-templatedb
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmftemplate
    volumes:
      - template-data-volume-dev:/data/db

  natsserver: 
    image: nats
    restart: always
    ports:
      - 4222
      - 6222
      - 8222

# put all the volume listings here for persistent data
volumes:
  template-data-volume-dev:
  checklist-data-volume-dev:
  score-data-volume-dev: