docker rmi -f cingulara/openstig-api-controls:0.6
docker rmi -f cingulara/openstig-api-read:0.6
docker rmi -f cingulara/openstig-api-compliance:0.6
docker rmi -f cingulara/openstig-web:0.6
docker rmi -f cingulara/openstig-api-upload:0.6
docker rmi -f cingulara/openstig-api-template:0.6
docker rmi -f cingulara/openstig-api-save:0.6
docker rmi -f cingulara/openstig-msg-score:0.6
docker rmi -f cingulara/openstig-api-scoring:0.6