apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrmf-msg-checklist
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: openrmf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/component: checklist-nats-message-client
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/revision: "{{ .Release.Revision }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      run: openrmf-msg-checklist
  replicas: 1
  template:
    metadata:
      labels:
        run: openrmf-msg-checklist
    spec:
      containers:
      - name: openrmf-msg-checklist
        image: docker.io/cingulara/openrmf-msg-checklist:{{.Values.checklistmsgImage}}
        env:
        - name: NATSSERVERURL
          value: nats://natsserver:4222
        - name: DBCONNECTION
          valueFrom:  
            secretKeyRef:
              name: checklistdbsecret
              key: appConnection
        - name: DB
          valueFrom:  
            secretKeyRef:
              name: checklistdbsecret
              key: initDBName
        - name: DBTYPE
          value: {{.Values.checklistdbtype}}
        resources:
          limits:
            memory: "750M"
            cpu: "250m"
          requests:
            memory: "250M"
            cpu: "100m"