---
# Source: openrmf/templates/scoremsg.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrmf-msg-score
  namespace: openrmf
  labels:
    app: openrmf
    chart: openrmf-1.0.0
    component: score-nats-message-client
    release: release-name
    revision: "0"
spec:
  selector:
    matchLabels:
      run: openrmf-msg-score
  replicas: 1
  template:
    metadata:
      labels:
        run: openrmf-msg-score
    spec:
      containers:
      - name: openrmf-msg-score
        image: cingulara/openrmf-msg-score:0.8
        ports:
        - containerPort: 8080
        env:
        - name: NATSSERVERURL
          value: nats://natsserver:4222
        - name: MONGODBCONNECTION
          value: mongodb://openrmfscore:openrmf1234!@openrmf-scoredb/openrmfscore?authSource=openrmfscore
        - name: MONGODB
          value: openrmfscore
        resources:
          limits:
            memory: "1Gi"
            cpu: "250m"
          requests:
            memory: "500M"
            cpu: "100m"